---
- hosts: clients
  gather_facts: no
  tasks:
    - name: Download image from GitHub
      get_url:
        url: https://raw.githubusercontent.com/janhalen/os2-openclient-vnext/ansible-prototype/demo/playbooks/set_wallpaper/logo.png
        mode: '0444'
        dest: /home/logo.png

    - name: Change desktop background
      shell: |
        xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/workspace0/last-image -s /home/logo.png
      become: yes
      become_user: root
...